import { CardItem, DealEvent } from "@/component/main/MainCard";
import card_thumb from "../../../public/image/home/server/card_thumb.webp";
import card_thumb_white from "../../../public/image/home/server/card_thumb_white.webp";
import profile from "../../../public/image/home/server/user_profile.webp";

export const MOCK_PRODUCT_INFO: CardItem[] = [
  {
    id: "59660939",
    due: new Date(),
    tags: [],
    title: "폴로 랄프로렌 여성 케이블 꽈배기 니트, 4컬러 택1",
    price: 89000,
    groupPrice: true,
    purchasedTotal: 121300,
    retailPrice: 199000,
    recommandBenefit: true,
    thumbnail: card_thumb.src,
    userProfiles: [profile.src, profile.src, profile.src],
    liked: false,
    event: {
      type: DealEvent.LIVE,
      desc: "오늘 13시 라이브, 놓치지 마세요!",
    },
    storeId: "shinsaegae_food",
    storeName: "신세계푸드",
  },
  {
    id: "59660939",
    due: new Date(),
    tags: ["free_deliver", "1천원 쿠폰할인"],
    title: "닥터방기원 맥주효모 샴푸1L+200ml 추가+샤쉐",
    price: 89000,
    groupPrice: false,
    purchasedTotal: 121300,
    retailPrice: 199000,
    recommandBenefit: true,
    thumbnail: card_thumb_white.src,
    userProfiles: [profile.src, profile.src, profile.src],
    liked: false,
    storeId: "shinsaegae_food",
    storeName: "신세계푸드",
  },
  {
    id: "59660939",
    due: new Date(),
    tags: ["free_deliver", "앵콜톡딜"],
    title: "폴로 랄프로렌 여성 케이블 꽈배기 니트, 4컬러",
    price: 89000,
    groupPrice: false,
    purchasedTotal: 121300,
    retailPrice: 199000,
    recommandBenefit: true,
    userProfiles: [profile.src, profile.src, profile.src],
    liked: false,
    thumbnail: card_thumb.src,
    event: {
      type: DealEvent.EVENT,
      desc: "폴로 새해맞이 브랜드 특별 세일!",
    },
    storeId: "shinsaegae_food",
    storeName: "신세계푸드",
  },
  {
    id: "59660939",
    due: new Date(),
    tags: ["5% 쿠폰할인"],
    title: "닥터방기원 맥주효모 샴푸1L+200ml",
    price: 89000,
    groupPrice: true,
    purchasedTotal: 121300,
    retailPrice: 199000,
    recommandBenefit: false,
    thumbnail: card_thumb_white.src,
    userProfiles: [profile.src, profile.src, profile.src],
    liked: false,
    event: {
      type: DealEvent.LIVE,
      desc: "라이브 혜택은 계속 진행 중!",
    },
    storeId: "shinsaegae_food",
    storeName: "신세계푸드",
  },
];
